// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace GProjectGameplayTags
{
	//InputTag
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Movement);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Movement_Move);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Movement_Jump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Movement_Sprint);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combat_BasicAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combat_StrongAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combat_WeaponAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combat_Parry);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Accessory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Targeting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Targeting_LockOn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Camera_Look);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction_Interact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction_UseItem);
	//State
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Character_Dead);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Character_Invulnerable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Airborne);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Dashing);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_AirAttackUsed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Hitstun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Knockdown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Parrying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_ParryWindow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Targeting_LockOn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Pickup);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_Attack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_Parry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_HitReact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_Knockdown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Movement_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill_Accessory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Targeting_LockOn);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Root);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_Combat_BasicAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_Combat_StrongAttack);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Combo_Window_Open);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Combo_Window_Close);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Attack_Trace_Begin);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Attack_Trace_Tick);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Attack_Trace_End);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Parry_Success);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Parry_Window_Close);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_HitReact);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_React_Parried);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Knockdown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Interaction_Pickup);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Interaction_UseItem);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Combat_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Resource_SP_Modifier);
}
